/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VpnConnectionsService } from "../vpnConnections.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VpnConnectionsCreateInput } from "./VpnConnectionsCreateInput";
import { VpnConnections } from "./VpnConnections";
import { VpnConnectionsFindManyArgs } from "./VpnConnectionsFindManyArgs";
import { VpnConnectionsWhereUniqueInput } from "./VpnConnectionsWhereUniqueInput";
import { VpnConnectionsUpdateInput } from "./VpnConnectionsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VpnConnectionsControllerBase {
  constructor(
    protected readonly service: VpnConnectionsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VpnConnections })
  @nestAccessControl.UseRoles({
    resource: "VpnConnections",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVpnConnections(
    @common.Body() data: VpnConnectionsCreateInput
  ): Promise<VpnConnections> {
    return await this.service.createVpnConnections({
      data: {
        ...data,

        serverLocation: data.serverLocation
          ? {
              connect: data.serverLocation,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        connectionTime: true,
        createdAt: true,
        disconnectionTime: true,
        id: true,

        serverLocation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VpnConnections] })
  @ApiNestedQuery(VpnConnectionsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VpnConnections",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vpnConnectionsItems(
    @common.Req() request: Request
  ): Promise<VpnConnections[]> {
    const args = plainToClass(VpnConnectionsFindManyArgs, request.query);
    return this.service.vpnConnectionsItems({
      ...args,
      select: {
        connectionTime: true,
        createdAt: true,
        disconnectionTime: true,
        id: true,

        serverLocation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VpnConnections })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VpnConnections",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vpnConnections(
    @common.Param() params: VpnConnectionsWhereUniqueInput
  ): Promise<VpnConnections | null> {
    const result = await this.service.vpnConnections({
      where: params,
      select: {
        connectionTime: true,
        createdAt: true,
        disconnectionTime: true,
        id: true,

        serverLocation: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VpnConnections })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VpnConnections",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVpnConnections(
    @common.Param() params: VpnConnectionsWhereUniqueInput,
    @common.Body() data: VpnConnectionsUpdateInput
  ): Promise<VpnConnections | null> {
    try {
      return await this.service.updateVpnConnections({
        where: params,
        data: {
          ...data,

          serverLocation: data.serverLocation
            ? {
                connect: data.serverLocation,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          connectionTime: true,
          createdAt: true,
          disconnectionTime: true,
          id: true,

          serverLocation: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VpnConnections })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VpnConnections",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVpnConnections(
    @common.Param() params: VpnConnectionsWhereUniqueInput
  ): Promise<VpnConnections | null> {
    try {
      return await this.service.deleteVpnConnections({
        where: params,
        select: {
          connectionTime: true,
          createdAt: true,
          disconnectionTime: true,
          id: true,

          serverLocation: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
